// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "1431. Kids With the Greatest Number of Candies",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "1431. Kids With the Greatest Number of Candies",
            targets: ["AppModule"],
            bundleIdentifier: "co.maximSamodurov.test.-431--Kids-With-the-Greatest-Number-of-Candies",
            teamIdentifier: "9Q4SAV9L28",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .bandage),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
